//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyMelsRestService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrazyMelsRestServiceEntities : DbContext
    {
        public CrazyMelsRestServiceEntities()
            : base("name=CrazyMelsRestServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_Cart> C_Cart { get; set; }
        public DbSet<C_Customer> C_Customer { get; set; }
        public DbSet<C_Order> C_Order { get; set; }
        public DbSet<C_Product> C_Product { get; set; }
    }
}
